"""agregar origen a telemetria y permitir lectura manual solo gas

Revision ID: 0d76e357393a
Revises: 4ff2deab983b
Create Date: 2026-09-18 09:53:48.649679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0d76e357393a'
down_revision: Union[str, None] = '4ff2deab983b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Mismo fix ya usado en 9dd2b7ffdaeb para el bug conocido de Alembic+Enum en
# Postgres con op.add_column sobre una tabla YA EXISTENTE: el autogenerate
# intenta crear el tipo enum inline como parte del add_column, lo que falla
# - hay que crearlo explicitamente antes (checkfirst=True, idempotente) y
# pasar create_type=False en la columna para que no lo intente de nuevo.
origen_lectura_enum = postgresql.ENUM('SENSOR', 'MANUAL', name='origen_lectura')


def upgrade() -> None:
    # NivelAlerta gano un valor nuevo (SIN_CLASIFICAR, ver
    # docs/PROJECT_CONTEXT.md) para lecturas manuales con datos incompletos
    # que no pudieron pasar por el pipeline ML. Alembic autogenerate no
    # detecta cambios de VALORES dentro de un enum de Postgres ya existente
    # (solo columnas/tablas nuevas), asi que este ALTER TYPE se agrego a
    # mano - no aparece en el diff automatico de mas abajo. IF NOT EXISTS lo
    # hace idempotente. 'SIN_CLASIFICAR' en mayusculas porque SQLAlchemy
    # Enum guarda el NAME del miembro Python en la columna nativa de
    # Postgres, no su .value (confirmado contra nivel_alerta ya existente:
    # SELECT enumlabel FROM pg_enum -> 'OPTIMO'/'ALERTA'/'CRITICO', no
    # minuscula). ADD VALUE no puede usarse en la misma transaccion en la
    # que ese valor nuevo se lee/escribe, pero aqui solo se agrega el valor,
    # no se usa todavia - seguro dentro de la transaccion de la migracion.
    op.execute("ALTER TYPE nivel_alerta ADD VALUE IF NOT EXISTS 'SIN_CLASIFICAR'")

    # ### commands auto generated by Alembic - please adjust! ###
    origen_lectura_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('telemetrias', sa.Column('origen', sa.Enum('SENSOR', 'MANUAL', name='origen_lectura', create_type=False), server_default='SENSOR', nullable=False))
    op.alter_column('telemetrias', 'temperatura',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('telemetrias', 'humedad',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('telemetrias', 'bateria',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telemetrias', 'bateria',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('telemetrias', 'humedad',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('telemetrias', 'temperatura',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('telemetrias', 'origen')
    # ### end Alembic commands ###

    origen_lectura_enum.drop(op.get_bind(), checkfirst=True)

    # NOTA: Postgres no soporta remover un valor de un tipo ENUM (no existe
    # "ALTER TYPE ... DROP VALUE"), asi que 'SIN_CLASIFICAR' NO se puede
    # quitar de nivel_alerta en downgrade - limitacion conocida de Postgres,
    # no un olvido. Si se necesita revertir de verdad, la unica via es
    # recrear el tipo entero (crear uno nuevo sin ese valor, migrar la
    # columna, borrar el viejo) - no se hizo aqui por ser una migracion
    # destructiva/riesgosa que nadie pidio explicitamente. Ademas, revertir
    # esta migracion con filas que ya quedaron en NivelAlerta.SIN_CLASIFICAR
    # o con temperatura/humedad/bateria en NULL (lecturas manuales solo-gas)
    # dejaria esas filas en un estado invalido para las columnas NOT NULL
    # que este downgrade intenta restaurar - Postgres rechazara el
    # downgrade si existen filas asi, lo cual es el comportamiento correcto
    # (no hay forma segura de inventar esos valores).
