"""agregar gas_corregido_porcentaje a telemetria

Revision ID: 1f707bee2405
Revises: 644c76760a40
Create Date: 2026-09-15 15:51:39.009985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f707bee2405'
down_revision: Union[str, None] = '644c76760a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetrias', sa.Column('gas_corregido_porcentaje', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telemetrias', 'gas_corregido_porcentaje')
    # ### end Alembic commands ###
