"""agregar tabla oauth_exchange_codes

Revision ID: 4ff2deab983b
Revises: 1f707bee2405
Create Date: 2026-09-17 10:21:28.515850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff2deab983b'
down_revision: Union[str, None] = '1f707bee2405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_exchange_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.Enum('LOGIN', 'REGISTRO_PENDIENTE', name='tipo_exchange_oauth'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nombre_google', sa.String(length=150), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_exchange_codes_codigo'), 'oauth_exchange_codes', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_exchange_codes_codigo'), table_name='oauth_exchange_codes')
    op.drop_table('oauth_exchange_codes')
    # ### end Alembic commands ###
