"""agregar tabla solicitudes de cambio de punto de control

Revision ID: 5c10ed6fdbf2
Revises: 9bd40f47ac1e
Create Date: 2026-09-13 11:49:52.804406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c10ed6fdbf2'
down_revision: Union[str, None] = '9bd40f47ac1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_cambio_punto_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CREAR', 'EDITAR', 'ELIMINAR', name='tipo_solicitud_cambio'), nullable=False),
    sa.Column('punto_control_id', sa.Integer(), nullable=True),
    sa.Column('datos_propuestos', sa.JSON(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADA', 'RECHAZADA', name='estado_solicitud_cambio'), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.Column('revisado_por_id', sa.Integer(), nullable=True),
    sa.Column('comentario_revision', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_revision', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['punto_control_id'], ['puntos_control.id'], ),
    sa.ForeignKeyConstraint(['revisado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_cambio_punto_control')
    # ### end Alembic commands ###
