"""agregar fecha_creacion y fecha_actualizacion a bitacora_alertas

Revision ID: 644c76760a40
Revises: 5c10ed6fdbf2
Create Date: 2026-09-15 15:22:46.495104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644c76760a40'
down_revision: Union[str, None] = '5c10ed6fdbf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bitacora_alertas', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bitacora_alertas', sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bitacora_alertas', 'fecha_actualizacion')
    op.drop_column('bitacora_alertas', 'fecha_creacion')
    # ### end Alembic commands ###
