"""permitir nulos en modelo_id, error_predicho y gas_corregido de telemetria

Revision ID: 726af7de96b3
Revises: 9250f91baf16
Create Date: 2026-09-12 15:39:38.403550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726af7de96b3'
down_revision: Union[str, None] = '9250f91baf16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telemetrias', 'modelo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('telemetrias', 'error_predicho',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('telemetrias', 'gas_corregido',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telemetrias', 'gas_corregido',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('telemetrias', 'error_predicho',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('telemetrias', 'modelo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
