"""migracion inicial - estacion, usuario, punto_control, modelo_ml, telemetria, bitacora_alertas

Revision ID: 7ebd0107e308
Revises: 
Create Date: 2026-09-12 13:35:15.629624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebd0107e308'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelos_ml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archivo_modelo', sa.String(length=255), nullable=False),
    sa.Column('archivo_scaler', sa.String(length=255), nullable=False),
    sa.Column('variables_entrada', sa.JSON(), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('TRABAJADOR', 'SUPERVISOR', 'ADMIN', name='rol_usuario'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('puntos_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre_estacion', sa.String(length=150), nullable=False),
    sa.Column('coord_x', sa.Float(), nullable=False),
    sa.Column('coord_y', sa.Float(), nullable=False),
    sa.Column('coord_z', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estacion_id'], ['estaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetrias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('punto_id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('humedad', sa.Float(), nullable=False),
    sa.Column('bateria', sa.Float(), nullable=False),
    sa.Column('gas_crudo', sa.Float(), nullable=False),
    sa.Column('error_predicho', sa.Float(), nullable=False),
    sa.Column('gas_corregido', sa.Float(), nullable=False),
    sa.Column('nivel_alerta', sa.Enum('OPTIMO', 'ALERTA', 'CRITICO', name='nivel_alerta'), nullable=False),
    sa.Column('estado_validacion', sa.Enum('VALIDO', 'DESCARTADO', name='estado_validacion'), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_ml.id'], ),
    sa.ForeignKeyConstraint(['punto_id'], ['puntos_control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetrias_timestamp'), 'telemetrias', ['timestamp'], unique=False)
    op.create_table('bitacora_alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telemetria_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'MUTEADA', 'RESUELTA', name='estado_alerta'), nullable=False),
    sa.Column('observacion_hse', sa.Text(), nullable=True),
    sa.Column('usuario_resolutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['telemetria_id'], ['telemetrias.id'], ),
    sa.ForeignKeyConstraint(['usuario_resolutor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bitacora_alertas')
    op.drop_index(op.f('ix_telemetrias_timestamp'), table_name='telemetrias')
    op.drop_table('telemetrias')
    op.drop_table('puntos_control')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('modelos_ml')
    op.drop_table('estaciones')
    # ### end Alembic commands ###
