"""agregar datos personales y numero de documento unico a usuario

Revision ID: 9bd40f47ac1e
Revises: 726af7de96b3
Create Date: 2026-09-12 17:41:01.491904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9bd40f47ac1e'
down_revision: Union[str, None] = '726af7de96b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


tipo_documento_enum = postgresql.ENUM('CC', 'CE', 'PASAPORTE', name='tipo_documento')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tipo_documento_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('usuarios', sa.Column('nombre', sa.String(length=150), nullable=False))
    op.add_column('usuarios', sa.Column('apellidos', sa.String(length=150), nullable=False))
    op.add_column('usuarios', sa.Column('telefono', sa.String(length=30), nullable=False))
    op.add_column('usuarios', sa.Column('tipo_documento', sa.Enum('CC', 'CE', 'PASAPORTE', name='tipo_documento', create_type=False), nullable=False))
    op.add_column('usuarios', sa.Column('numero_documento', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_usuarios_numero_documento'), 'usuarios', ['numero_documento'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_numero_documento'), table_name='usuarios')
    op.drop_column('usuarios', 'numero_documento')
    op.drop_column('usuarios', 'tipo_documento')
    op.drop_column('usuarios', 'telefono')
    op.drop_column('usuarios', 'apellidos')
    op.drop_column('usuarios', 'nombre')
    tipo_documento_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
