"""agregar campos de autenticacion password y google a usuario

Revision ID: 9dd2b7ffdaeb
Revises: 7ebd0107e308
Create Date: 2026-09-12 13:38:00.256444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9dd2b7ffdaeb'
down_revision: Union[str, None] = '7ebd0107e308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


metodo_registro_enum = postgresql.ENUM('GOOGLE', 'PASSWORD', name='metodo_registro')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    metodo_registro_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('usuarios', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('metodo_registro', sa.Enum('GOOGLE', 'PASSWORD', name='metodo_registro', create_type=False), nullable=False))
    op.add_column('usuarios', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_usuarios_google_id'), 'usuarios', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_google_id'), table_name='usuarios')
    op.drop_column('usuarios', 'fecha_creacion')
    op.drop_column('usuarios', 'metodo_registro')
    op.drop_column('usuarios', 'google_id')
    op.drop_column('usuarios', 'password_hash')
    metodo_registro_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
